 ## Array Basics


In [2]:
import numpy as np

In [3]:
fruits = ['apple', 'banana', 'cherry', 'date']

In [4]:
arr_1 = np.array(fruits)
print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [5]:
print(arr_1.dtype)

<U6


Unicode string? and 6 is the max length of one of the strings which is banana

In [6]:
arr_2 = np.array([[10, 11, 12], [13, 14, 15]])
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [7]:
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


I guess this is the 2d view of it where the line 1 stuff is all on line one etc etc

In [8]:
arr_3 = np.array([[1, 3, 5], [2, 4, 6]])
print(arr_3)

[[1 3 5]
 [2 4 6]]


In [9]:
arr_4 = np.array([arr_3[0, 2], arr_3[1, 1]])
print(arr_4)

[5 4]


In [ ]:
arr_5 = np.ones((2, 2, 2)) # 2's are giving the length of the x y and z axis
print(arr_5)                 

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
