# Exercise 1.A NumPy: Manipulating Arrays

In [21]:
import numpy as np

 ## Looping Through Arrays

In [22]:
arrA = np.array([[11, 12, 13],[14, 15, 16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [23]:
for x in arrA:
    print(x*2)

[22 24 26]
[28 30 32]


In [24]:
for x in arrA:
    for y in x:
        print(y*2)

22
24
26
28
30
32


one loops over the rows of the array 
and the second one multipliues the individual elements

In [27]:
for x in arrA:
    for y in x:
        loopResult = x*2
        print(loopResult, arrA.ndim, arrA.shape) 

[22 24 26] 2 (2, 3)
[22 24 26] 2 (2, 3)
[22 24 26] 2 (2, 3)
[28 30 32] 2 (2, 3)
[28 30 32] 2 (2, 3)
[28 30 32] 2 (2, 3)


so the first part multiplies the row and then the second part prints the row for each element in the row

## Joining and Stacking Arrays

In [29]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)


[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [31]:
joined_array_2 =  np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [34]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [35]:
another2 = np.concatenate((joined_array_1, arrA), axis = 1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

basically this would leave a big hole in the array in the bottom left sad!

In [42]:
arrH = np.hstack((arrA,arrA))
arrV =np.vstack((arrA,arrA))
arrD = np.dstack((arrA,arrA))
print(arrH, arrH.ndim, arrH.shape)
print(arrV, arrV.ndim, arrV.shape)
print(arrD, arrD.ndim, arrD.shape)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]] 2 (2, 6)
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]] 2 (4, 3)
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]] 3 (2, 3, 2)


stacks horizantally 
stacks verically 
stacks z axiz

 ## Splitting Arrays

In [52]:
splitsky = np.array_split(joined_array_1,2)
print(splitsky)

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


why did it do this, Im scared, Ill have a screenshot ready if this looks normal on the repo

In [49]:
splitsky = np.array_split(joined_array_1,1)
print(splitsky)

[array([[11, 12, 13],
       [14, 15, 16],
       [11, 12, 13],
       [14, 15, 16]])]


In [50]:
# ok well this one didnt do anthing

In [55]:
# I think the first one isnt displaying properly but Im assuming as the thing implies it just splits them apart horizantally like below

In [54]:
splitsky = np.array_split(joined_array_1,2)
print(splitsky[0])
print(splitsky[1])

[[11 12 13]
 [14 15 16]]
[[11 12 13]
 [14 15 16]]


In [58]:
spliterino = np.array_split(joined_array_1,3)
print(spliterino)

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


In [59]:
# I guess it ran out of space to split evenly

## Searching and Replacing Array


In [63]:
result_1 = np.where(arrA %2 == 0,arrA, 'odd' )
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [65]:
arrB = np.array([[7,6], [13,5], [7,3]])
print(arrB)

[[ 7  6]
 [13  5]
 [ 7  3]]


In [66]:
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [69]:
print(arrB)
print("~~~~~~~~~~~")
z = arrB<7
arrC = arrB[z]
print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
~~~~~~~~~~~
[6 5 3]


In [71]:
aa = arrB>=7
arrd = arrB[aa]
print(arrd)

[ 7 13  7]
