# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random Numbers

In [2]:
r_1 = np.random.randint(1, 21, size=2)
print(r_1)

[3 9]


In [3]:
r_2 = np.random.randint(1, 21, size=(1, 2))
print(r_2)

[[10 17]]


In [6]:
r_3 = np.random.rand(2, 1)
print(r_3)

[[0.28394197]
 [0.25317409]]


In [7]:
r_4 = np.random.randint(20, 101, size=(4, 5))
print(r_4)

[[85 94 35 55 70]
 [62 36 82 67 71]
 [50 34 75 41 87]
 [91 92 32 82 40]]


In [8]:
r_5 = np.random.rand(4, 5)
print(r_5)

[[0.49940286 0.21328362 0.26947569 0.82915918 0.08965074]
 [0.82743273 0.2193514  0.81679223 0.21023185 0.48957159]
 [0.75954423 0.08085805 0.05288865 0.12300116 0.81247615]
 [0.70599971 0.70538559 0.5501128  0.13194576 0.37734392]]


## Generating Random Choices from

In [10]:

students = np.array(["Alice", "Bob", "Charlie", "David", "Ella", "Frank", 
"Grace", "Henry", "Ivy", "Jack", "Kara", "Liam"])

In [11]:
callOn = np.random.choice(students)
print(callOn)

Jack


In [13]:
breakoutGroups = np.random.choice(students, size=12, replace=False).reshape(3, 4)
print(breakoutGroups)

[['Bob' 'Ella' 'Alice' 'Grace']
 ['Charlie' 'Henry' 'Kara' 'Ivy']
 ['Liam' 'Jack' 'David' 'Frank']]


groups arent balanced by any metric such as skill level

In [17]:
p_values = [0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.00, 0.07, 0.30]
# I wanted something I can just copy and paste over and over I dont want to type out that many unique values
callOnWeighted = np.random.choice(students, size=5, replace=False, p = p_values)
print(callOnWeighted)

['Liam' 'Grace' 'Henry' 'David' 'Charlie']


## Generating a Normal Distribution

In [19]:
bellCurve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(bellCurve)

[[ 3.10693838 14.75074676 16.5930224  15.74297047 11.26574832]
 [11.14461523 11.20477316 13.04815674  7.6133249  10.85826056]
 [ 7.35852422 11.92138862 13.69196152 13.1769878   9.23654943]
 [10.05787223  9.41647079  4.79114914 12.79649835  6.65305064]]
