# Exercise 1.C Performing operations on arrays

## Sample Arrays.

In [102]:
import numpy as np

In [103]:


r_1 = np.random.randint(1, 21, size=2)
r_2 = np.random.randint(1, 21, size=(1, 2))
r_3 = np.random.rand(2, 1)
r_4 = np.random.randint(20, 101, size=(4, 5))
r_5 = np.random.rand(4, 5)


 ## Permutations


In [104]:

print(r_4)

[[76 67 72 46 26]
 [20 47 51 61 78]
 [71 49 51 28 98]
 [55 25 39 39 21]]


In [105]:
np.random.shuffle(r_4)

print(r_4)

[[55 25 39 39 21]
 [76 67 72 46 26]
 [71 49 51 28 98]
 [20 47 51 61 78]]


it just moves the rows up and down

In [106]:
new_shuffle = np.random.permutation(r_4)

In [107]:
print(new_shuffle)

[[76 67 72 46 26]
 [71 49 51 28 98]
 [20 47 51 61 78]
 [55 25 39 39 21]]


shuffle reorders the original array while permutation is a new version of it, leaving the original unchanged

## Mathematical Operations

In [108]:
print("r_1", r_1)
print("Shape:", r_1.shape)
print("r_2", r_2)
print("Shape:", r_2.shape)

result_add = np.add(r_1, r_2)
print("\nr_1 + r_2 =", result_add)
print("Shape:", result_add.shape)

r_1 [12 16]
Shape: (2,)
r_2 [[16 12]]
Shape: (1, 2)

r_1 + r_2 = [[28 28]]
Shape: (1, 2)


In [109]:
print("r_1", r_1)
print("Shape:", r_1.shape)
print("r_3", r_3)
print("Shape:", r_3.shape)

result_add = np.add(r_1, r_3)
print("\nr_1 + r_3 =", result_add)
print("Shape:", result_add.shape)

r_1 [12 16]
Shape: (2,)
r_3 [[0.57823871]
 [0.43356735]]
Shape: (2, 1)

r_1 + r_3 = [[12.57823871 16.57823871]
 [12.43356735 16.43356735]]
Shape: (2, 2)


In [110]:
print("r_2", r_2)
print("Shape:", r_2.shape)
print("r_4", r_4)
print("Shape:", r_4.shape)

#result_add = np.add(r_2, r_4)
#ValueError: operands could not be broadcast together with shapes (1,2) (4,5)

r_2 [[16 12]]
Shape: (1, 2)
r_4 [[55 25 39 39 21]
 [76 67 72 46 26]
 [71 49 51 28 98]
 [20 47 51 61 78]]
Shape: (4, 5)


In [111]:

try:
    print(np.add(r_1, r_4))
except ValueError as e:
    print("error when adding r_1 and r_4:", e)


try:
    print(np.add(r_2, r_4))
except ValueError as e:
    print("error when adding r_2 and r_4:", e)

try:
    print(np.add(r_3, r_4))
except ValueError as e:
    print("error when adding r_3 and r_4:", e)

error when adding r_1 and r_4: operands could not be broadcast together with shapes (2,) (4,5) 
error when adding r_2 and r_4: operands could not be broadcast together with shapes (1,2) (4,5) 
error when adding r_3 and r_4: operands could not be broadcast together with shapes (2,1) (4,5) 


more sad shapes...

In [112]:
print("r_4:\n", r_4)
print("\nr_4 + np.array([1]):\n", np.add(r_4, np.array([1])))
print("\nr_4 + np.array([[1]]):\n", np.add(r_4, np.array([[1]])))
print("\nr_4 + np.array([1,1,1,1,1]):\n", np.add(r_4, np.array([1,1,1,1,1])))

r_4:
 [[55 25 39 39 21]
 [76 67 72 46 26]
 [71 49 51 28 98]
 [20 47 51 61 78]]

r_4 + np.array([1]):
 [[56 26 40 40 22]
 [77 68 73 47 27]
 [72 50 52 29 99]
 [21 48 52 62 79]]

r_4 + np.array([[1]]):
 [[56 26 40 40 22]
 [77 68 73 47 27]
 [72 50 52 29 99]
 [21 48 52 62 79]]

r_4 + np.array([1,1,1,1,1]):
 [[56 26 40 40 22]
 [77 68 73 47 27]
 [72 50 52 29 99]
 [21 48 52 62 79]]


broadcasting....

In [113]:
try:
    print(np.add(r_4, np.array([[1],[1]])))
except ValueError as e:
    print("error adding np.array([[1],[1]]) to r_4:", e)
#array shape (2,1) cannot broadcast with (3,4) because the  1 would need to match 4 or be 1, the 2 can't broadcast to 3.

error adding np.array([[1],[1]]) to r_4: operands could not be broadcast together with shapes (4,5) (2,1) 


broadcasting lets you combine arrays of different shapes 

the dimensions can work if they are equal or one is = to 1


np.add = smaller array gets stretched to the match the bigger array (kind of) 
takes the maximum between the two variables for the particular dimension.

so

(1,2) + (1,) would be (1,2) scalar
(3,4) + (1,4) would be (3,4) row vector
(3,4) + (3,1) would be (3,4) column

 ## Rounding

In [114]:
print("r_3:\n", r_3)

r_3:
 [[0.57823871]
 [0.43356735]]


In [115]:
print("trunc:", np.trunc(r_3))
print("fix:", np.fix(r_3))
print("floor:", np.floor(r_3))
print("ceil:", np.ceil(r_3))
print("round:", np.round(r_3, 2))

trunc: [[0.]
 [0.]]
fix: [[0.]
 [0.]]
floor: [[0.]
 [0.]]
ceil: [[1.]
 [1.]]
round: [[0.58]
 [0.43]]


these results are kinda sad!

## Cumulative Operations

In [116]:

print("r_4:\n", r_4)
print("sum of all elements:", np.sum(r_4))
print("sum along (columns):", np.sum(r_4, axis=0))
print("sum along (rows):   ", np.sum(r_4, axis=1))
print("cumulative sum (flattened):", np.cumsum(r_4))
print("cumulative sum along axis 0:\n", np.cumsum(r_4, axis=0))

r_4:
 [[55 25 39 39 21]
 [76 67 72 46 26]
 [71 49 51 28 98]
 [20 47 51 61 78]]
sum of all elements: 1020
sum along (columns): [222 188 213 174 223]
sum along (rows):    [179 287 297 257]
cumulative sum (flattened): [  55   80  119  158  179  255  322  394  440  466  537  586  637  665
  763  783  830  881  942 1020]
cumulative sum along axis 0:
 [[ 55  25  39  39  21]
 [131  92 111  85  47]
 [202 141 162 113 145]
 [222 188 213 174 223]]


## Grocery Problem

In [117]:

bag1 = np.array([2, 3, 4, 0]) # 2 veg, 3 fruit, 4 snacks, 0 beverages
bag2 = np.array([4, 0, 1, 2]) # 4 veg, 0 fruit, 1 snack, 2 beverages

print("bag1\n", bag1)
print("bag2\n", bag2)

bag1
 [2 3 4 0]
bag2
 [4 0 1 2]


In [118]:
totalBag1 = np.sum(bag1)
totalBag2 = np.sum(bag2)
print(f"The first bag has {totalBag1} items, and the second bag has {totalBag2} items.")

The first bag has 9 items, and the second bag has 7 items.


In [119]:
totalPerCategory = bag1 + bag2
print(f"There are {totalPerCategory[0]} vegetables, {totalPerCategory[1]} fruits, {totalPerCategory[2]} snacks, and {totalPerCategory[3]} beverages in the bags.")

There are 6 vegetables, 3 fruits, 5 snacks, and 2 beverages in the bags.


## Teamwork

In [120]:
ali = np.array([5, 4, 6, 4, 2])
ben = np.array([0, 5, 5, 3, 4])
carla = np.array([3, 6, 0, 3, 4])

# array
allKnocks = np.array([ali, ben, carla])
print("All knocks:\n", allKnocks)

All knocks:
 [[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [121]:
# per person
personTotals = np.sum(allKnocks, axis=1)
# the group 
groupTotal = np.sum(allKnocks)

print("per person:", personTotals)
print("group total:", groupTotal)

per person: [21 17 16]
group total: 54


In [ ]:
# rolling total by day
dailyTotal = np.sum(allKnocks, axis=0)      # shape (5,?)

estimatedVotes = dailyTotal // 2            # one in two will actually vote
print("doorknocks:", dailyTotal)
print("total expected votes per day:", estimatedVotes)

doorknocks: [ 8 15 11 10 10]
total expected votes per day: [4 7 5 5 5]
